manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/kotkota
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
  self:
    path: config